### ISSUE TITLE
landscape of biomedical research for specific topic

### ISSUE THREAD

**Issue by zinojeng** [berenslab/pubmed-landscape#1]
Could I create our own landscape of biomedical research, for example: **Metformin**

Thanks!

**Comment by ritagonmar** [comment]
Hi, 
I don't know exactly what you mean. One can of course use the same pipeline that we use for any collection of documents, so if you have a set of papers from a discipline of your interest, you could run the pipeline and get a 2D embedding like the one we have.That way you would have your own landscape!
